#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

exec 1>&2

CURRENT_DIR="$(pwd)"
HAS_ERROR=""

for file in $(git diff --cached --name-only | sort | uniq); do
	file_size=$(du -m $CURRENT_DIR/$file | awk '{print $1}')
	if [ "$file_size" -ge 5 ]; then
		echo "$file is over 5MB."
		HAS_ERROR="1"
	fi
done

if [ "$HAS_ERROR" != "" ]; then
    echo "Can't commit, fix errors first." >&2
    exit 1
fi

exit 0